### ISSUE TITLE
Research not getting researched

### ISSUE THREAD

**Issue by Frede175** [Lomztein/Brute-Force-Attack-2#70]
If you have an ongoing research and start a new one, it disappears from the list but does not shown up in the current research list. The research/upgrade might be applied, since it shows two research done, but two with the same name.

Reproduce:
- Load any map
- Research Unlock death
- After two rounds start the +10% Blue Firerate
[Player.log](https://github.com/Lomztein/Brute-Force-Attack-2/files/5599708/Player-prev.log)

**Comment by Lomztein** [comment]
This is not a bug,  +10% Blue Firerate is instant. A "Waves: Instant" has now been added to the research option in the list, to make this clearer. Additionally, a "Research 'xyz' completed." message is now displayed for both instant and delayed research. This also fixed the double message bug and I have no idea how.
